-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flashDispatch is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    flashDemux2getPath_V_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    flashDemux2getPath_V_empty_n : IN STD_LOGIC;
    flashDemux2getPath_V_read : OUT STD_LOGIC;
    flash_Disp2rec_V_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    flash_Disp2rec_V_V_full_n : IN STD_LOGIC;
    flash_Disp2rec_V_V_write : OUT STD_LOGIC;
    memRdCmd_V_TREADY : IN STD_LOGIC;
    memRdCmd_V_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    memRdCmd_V_TVALID : OUT STD_LOGIC );
end;


architecture behav of flashDispatch is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal tmp_nbreadreq_fu_56_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_reg_144 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal memRdCmd_V_1_ack_in : STD_LOGIC;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal tmp_reg_144_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_block_state3_io : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal memRdCmd_V_1_data_out : STD_LOGIC_VECTOR (47 downto 0);
    signal memRdCmd_V_1_vld_in : STD_LOGIC;
    signal memRdCmd_V_1_vld_out : STD_LOGIC;
    signal memRdCmd_V_1_ack_out : STD_LOGIC;
    signal memRdCmd_V_1_payload_A : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal memRdCmd_V_1_payload_B : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal memRdCmd_V_1_sel_rd : STD_LOGIC := '0';
    signal memRdCmd_V_1_sel_wr : STD_LOGIC := '0';
    signal memRdCmd_V_1_sel : STD_LOGIC;
    signal memRdCmd_V_1_load_A : STD_LOGIC;
    signal memRdCmd_V_1_load_B : STD_LOGIC;
    signal memRdCmd_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal memRdCmd_V_1_state_cmp_full : STD_LOGIC;
    signal memRdCmd_V_TDATA_blk_n : STD_LOGIC;
    signal flashDemux2getPath_V_blk_n : STD_LOGIC;
    signal flash_Disp2rec_V_V_blk_n : STD_LOGIC;
    signal getCtrlWord_address_s_fu_84_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal getCtrlWord_address_s_reg_148 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal tmp_V_reg_153 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tmp_s_reg_159 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal tmp_1_cast_fu_139_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal op2_assign_fu_108_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_242_i_fu_115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_i_fu_120_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal getCtrlWord_count_V_fu_125_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_132_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    getCtrlWord_address_s_reg_148_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                getCtrlWord_address_s_reg_148 <= ap_const_lv32_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    getCtrlWord_address_s_reg_148 <= getCtrlWord_address_s_fu_84_p1;
                end if; 
            end if;
        end if;
    end process;


    memRdCmd_V_1_payload_A_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memRdCmd_V_1_payload_A <= ap_const_lv48_0;
            else
                if ((memRdCmd_V_1_load_A = ap_const_logic_1)) then 
                    memRdCmd_V_1_payload_A <= tmp_1_cast_fu_139_p1;
                end if; 
            end if;
        end if;
    end process;


    memRdCmd_V_1_payload_B_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memRdCmd_V_1_payload_B <= ap_const_lv48_0;
            else
                if ((memRdCmd_V_1_load_B = ap_const_logic_1)) then 
                    memRdCmd_V_1_payload_B <= tmp_1_cast_fu_139_p1;
                end if; 
            end if;
        end if;
    end process;


    memRdCmd_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memRdCmd_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((memRdCmd_V_1_ack_out = ap_const_logic_1) and (memRdCmd_V_1_vld_out = ap_const_logic_1))) then 
                                        memRdCmd_V_1_sel_rd <= not(memRdCmd_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    memRdCmd_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memRdCmd_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((memRdCmd_V_1_vld_in = ap_const_logic_1) and (memRdCmd_V_1_ack_in = ap_const_logic_1))) then 
                                        memRdCmd_V_1_sel_wr <= not(memRdCmd_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    memRdCmd_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memRdCmd_V_1_state <= ap_const_lv2_0;
            else
                if ((((memRdCmd_V_1_vld_in = ap_const_logic_0) and (memRdCmd_V_1_state = ap_const_lv2_2)) or ((memRdCmd_V_1_vld_in = ap_const_logic_0) and (memRdCmd_V_1_ack_out = ap_const_logic_1) and (memRdCmd_V_1_state = ap_const_lv2_3)))) then 
                    memRdCmd_V_1_state <= ap_const_lv2_2;
                elsif ((((memRdCmd_V_1_ack_out = ap_const_logic_0) and (memRdCmd_V_1_state = ap_const_lv2_1)) or ((memRdCmd_V_1_ack_out = ap_const_logic_0) and (memRdCmd_V_1_vld_in = ap_const_logic_1) and (memRdCmd_V_1_state = ap_const_lv2_3)))) then 
                    memRdCmd_V_1_state <= ap_const_lv2_1;
                elsif (((not(((memRdCmd_V_1_vld_in = ap_const_logic_0) and (memRdCmd_V_1_ack_out = ap_const_logic_1))) and not(((memRdCmd_V_1_ack_out = ap_const_logic_0) and (memRdCmd_V_1_vld_in = ap_const_logic_1))) and (memRdCmd_V_1_state = ap_const_lv2_3)) or ((memRdCmd_V_1_ack_out = ap_const_logic_1) and (memRdCmd_V_1_state = ap_const_lv2_1)) or ((memRdCmd_V_1_vld_in = ap_const_logic_1) and (memRdCmd_V_1_state = ap_const_lv2_2)))) then 
                    memRdCmd_V_1_state <= ap_const_lv2_3;
                else 
                    memRdCmd_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    tmp_V_reg_153_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_V_reg_153 <= ap_const_lv16_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    tmp_V_reg_153 <= flashDemux2getPath_V_dout(47 downto 32);
                end if; 
            end if;
        end if;
    end process;


    tmp_reg_144_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_reg_144 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    tmp_reg_144 <= (0=>flashDemux2getPath_V_empty_n, others=>'-');
                end if; 
            end if;
        end if;
    end process;


    tmp_reg_144_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_reg_144_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    tmp_reg_144_pp0_iter1_reg <= tmp_reg_144;
                end if; 
            end if;
        end if;
    end process;


    tmp_s_reg_159_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_s_reg_159 <= ap_const_lv13_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    tmp_s_reg_159 <= flashDemux2getPath_V_dout(47 downto 35);
                end if; 
            end if;
        end if;
    end process;


    ap_NS_iter0_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_iter0_fsm, flashDemux2getPath_V_empty_n, tmp_nbreadreq_fu_56_p3, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, flashDemux2getPath_V_empty_n, tmp_nbreadreq_fu_56_p3, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1))))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_done_reg, ap_CS_iter2_fsm, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and not(((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and ((ap_const_logic_0 = ap_CS_iter1_fsm_state2) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1))))))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, flashDemux2getPath_V_empty_n, tmp_nbreadreq_fu_56_p3)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)));
    end process;


    ap_block_state2_io_assign_proc : process(tmp_reg_144, memRdCmd_V_1_ack_in)
    begin
                ap_block_state2_io <= ((memRdCmd_V_1_ack_in = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(flash_Disp2rec_V_V_full_n, tmp_reg_144)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1));
    end process;


    ap_block_state3_io_assign_proc : process(memRdCmd_V_1_ack_in, tmp_reg_144_pp0_iter1_reg)
    begin
                ap_block_state3_io <= ((memRdCmd_V_1_ack_in = ap_const_logic_0) and (tmp_reg_144_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(memRdCmd_V_1_ack_in)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (memRdCmd_V_1_ack_in = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, memRdCmd_V_1_ack_in, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2getPath_V_empty_n, tmp_nbreadreq_fu_56_p3, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    flashDemux2getPath_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2getPath_V_empty_n, tmp_nbreadreq_fu_56_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            flashDemux2getPath_V_blk_n <= flashDemux2getPath_V_empty_n;
        else 
            flashDemux2getPath_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    flashDemux2getPath_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2getPath_V_empty_n, tmp_nbreadreq_fu_56_p3, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) or ((flashDemux2getPath_V_empty_n = ap_const_logic_0) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1)))) and (tmp_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            flashDemux2getPath_V_read <= ap_const_logic_1;
        else 
            flashDemux2getPath_V_read <= ap_const_logic_0;
        end if; 
    end process;


    flash_Disp2rec_V_V_blk_n_assign_proc : process(flash_Disp2rec_V_V_full_n, tmp_reg_144, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_reg_144 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            flash_Disp2rec_V_V_blk_n <= flash_Disp2rec_V_V_full_n;
        else 
            flash_Disp2rec_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    flash_Disp2rec_V_V_din <= tmp_V_reg_153;

    flash_Disp2rec_V_V_write_assign_proc : process(ap_done_reg, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and (tmp_reg_144 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            flash_Disp2rec_V_V_write <= ap_const_logic_1;
        else 
            flash_Disp2rec_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    getCtrlWord_address_s_fu_84_p1 <= flashDemux2getPath_V_dout(32 - 1 downto 0);
    getCtrlWord_count_V_fu_125_p3 <= 
        tmp_80_i_fu_120_p2 when (tmp_242_i_fu_115_p2(0) = '1') else 
        tmp_s_reg_159;
    memRdCmd_V_1_ack_in <= memRdCmd_V_1_state(1);
    memRdCmd_V_1_ack_out <= memRdCmd_V_TREADY;

    memRdCmd_V_1_data_out_assign_proc : process(memRdCmd_V_1_payload_A, memRdCmd_V_1_payload_B, memRdCmd_V_1_sel)
    begin
        if ((memRdCmd_V_1_sel = ap_const_logic_1)) then 
            memRdCmd_V_1_data_out <= memRdCmd_V_1_payload_B;
        else 
            memRdCmd_V_1_data_out <= memRdCmd_V_1_payload_A;
        end if; 
    end process;

    memRdCmd_V_1_load_A <= (memRdCmd_V_1_state_cmp_full and not(memRdCmd_V_1_sel_wr));
    memRdCmd_V_1_load_B <= (memRdCmd_V_1_state_cmp_full and memRdCmd_V_1_sel_wr);
    memRdCmd_V_1_sel <= memRdCmd_V_1_sel_rd;
    memRdCmd_V_1_state_cmp_full <= '0' when (memRdCmd_V_1_state = ap_const_lv2_1) else '1';

    memRdCmd_V_1_vld_in_assign_proc : process(ap_done_reg, flash_Disp2rec_V_V_full_n, tmp_reg_144, memRdCmd_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memRdCmd_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((flash_Disp2rec_V_V_full_n = ap_const_logic_0) and (tmp_reg_144 = ap_const_lv1_1)))) and (tmp_reg_144 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            memRdCmd_V_1_vld_in <= ap_const_logic_1;
        else 
            memRdCmd_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    memRdCmd_V_1_vld_out <= memRdCmd_V_1_state(0);
    memRdCmd_V_TDATA <= memRdCmd_V_1_data_out;

    memRdCmd_V_TDATA_blk_n_assign_proc : process(tmp_reg_144, ap_CS_iter1_fsm_state2, tmp_reg_144_pp0_iter1_reg, ap_CS_iter2_fsm_state3, memRdCmd_V_1_state)
    begin
        if ((((tmp_reg_144_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3)) or ((tmp_reg_144 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) then 
            memRdCmd_V_TDATA_blk_n <= memRdCmd_V_1_state(1);
        else 
            memRdCmd_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    memRdCmd_V_TVALID <= memRdCmd_V_1_state(0);
    op2_assign_fu_108_p3 <= (tmp_s_reg_159 & ap_const_lv3_0);
        tmp_1_cast_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_132_p3),48));

    tmp_1_fu_132_p3 <= (getCtrlWord_count_V_fu_125_p3 & getCtrlWord_address_s_reg_148);
    tmp_242_i_fu_115_p2 <= "1" when (unsigned(tmp_V_reg_153) > unsigned(op2_assign_fu_108_p3)) else "0";
    tmp_80_i_fu_120_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(tmp_s_reg_159));
    tmp_nbreadreq_fu_56_p3 <= (0=>flashDemux2getPath_V_empty_n, others=>'-');
end behav;
