// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "flashSetPathNoFilter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic flashSetPathNoFilter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic flashSetPathNoFilter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> flashSetPathNoFilter::ap_ST_iter0_fsm_state1 = "1";
const sc_lv<2> flashSetPathNoFilter::ap_ST_iter1_fsm_state2 = "10";
const sc_lv<2> flashSetPathNoFilter::ap_ST_iter2_fsm_state3 = "10";
const sc_lv<2> flashSetPathNoFilter::ap_ST_iter1_fsm_state0 = "1";
const sc_lv<2> flashSetPathNoFilter::ap_ST_iter2_fsm_state0 = "1";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool flashSetPathNoFilter::ap_const_boolean_1 = true;
const sc_lv<1> flashSetPathNoFilter::ap_const_lv1_0 = "0";
const sc_lv<1> flashSetPathNoFilter::ap_const_lv1_1 = "1";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_1 = "1";
const sc_lv<2> flashSetPathNoFilter::ap_const_lv2_0 = "00";
const sc_lv<2> flashSetPathNoFilter::ap_const_lv2_2 = "10";
const sc_lv<2> flashSetPathNoFilter::ap_const_lv2_3 = "11";
const sc_lv<2> flashSetPathNoFilter::ap_const_lv2_1 = "1";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_20 = "100000";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_2F = "101111";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_23 = "100011";
const sc_lv<3> flashSetPathNoFilter::ap_const_lv3_0 = "000";
const sc_lv<13> flashSetPathNoFilter::ap_const_lv13_1 = "1";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_40 = "1000000";
const sc_lv<32> flashSetPathNoFilter::ap_const_lv32_41 = "1000001";
const bool flashSetPathNoFilter::ap_const_boolean_0 = false;
const sc_lv<48> flashSetPathNoFilter::ap_const_lv48_0 = "000000000000000000000000000000000000000000000000";
const sc_lv<64> flashSetPathNoFilter::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<13> flashSetPathNoFilter::ap_const_lv13_0 = "0000000000000";

flashSetPathNoFilter::flashSetPathNoFilter(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_iter0_fsm_state1);
    sensitive << ( ap_CS_iter0_fsm );

    SC_METHOD(thread_ap_CS_iter1_fsm_state0);
    sensitive << ( ap_CS_iter1_fsm );

    SC_METHOD(thread_ap_CS_iter1_fsm_state2);
    sensitive << ( ap_CS_iter1_fsm );

    SC_METHOD(thread_ap_CS_iter2_fsm_state0);
    sensitive << ( ap_CS_iter2_fsm );

    SC_METHOD(thread_ap_CS_iter2_fsm_state3);
    sensitive << ( ap_CS_iter2_fsm );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );

    SC_METHOD(thread_ap_block_state2_io);
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( ap_predicate_op31_write_state2 );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_predicate_op34_write_state2 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_predicate_op41_write_state3 );
    sensitive << ( ap_predicate_op46_write_state3 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );

    SC_METHOD(thread_ap_condition_353);
    sensitive << ( ap_done_reg );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_ap_condition_472);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( grp_nbreadreq_fu_84_p3 );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_ap_condition_473);
    sensitive << ( tmp_445_nbreadreq_fu_76_p3 );
    sensitive << ( flashSetState );
    sensitive << ( tmp_451_fu_178_p3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( ap_CS_iter1_fsm_state0 );
    sensitive << ( ap_CS_iter2_fsm_state0 );

    SC_METHOD(thread_ap_predicate_op23_read_state1);
    sensitive << ( grp_nbreadreq_fu_84_p3 );
    sensitive << ( flashSetState );

    SC_METHOD(thread_ap_predicate_op31_write_state2);
    sensitive << ( flashSetState_load_reg_221 );
    sensitive << ( tmp_445_reg_225 );
    sensitive << ( tmp_448_reg_229 );
    sensitive << ( tmp_451_reg_248 );

    SC_METHOD(thread_ap_predicate_op34_write_state2);
    sensitive << ( flashSetState_load_reg_221 );
    sensitive << ( tmp_reg_252 );

    SC_METHOD(thread_ap_predicate_op41_write_state3);
    sensitive << ( flashSetState_load_reg_221_pp0_iter1_reg );
    sensitive << ( tmp_445_reg_225_pp0_iter1_reg );
    sensitive << ( tmp_448_reg_229_pp0_iter1_reg );
    sensitive << ( tmp_451_reg_248_pp0_iter1_reg );

    SC_METHOD(thread_ap_predicate_op46_write_state3);
    sensitive << ( flashSetState_load_reg_221_pp0_iter1_reg );
    sensitive << ( tmp_reg_252_pp0_iter1_reg );

    SC_METHOD(thread_ap_predicate_op9_read_state1);
    sensitive << ( tmp_445_nbreadreq_fu_76_p3 );
    sensitive << ( grp_nbreadreq_fu_84_p3 );
    sensitive << ( flashSetState );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_flashDemux2setPathMe_1_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );

    SC_METHOD(thread_flashDemux2setPathMe_1_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_flashDemux2setPathVa_1_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );

    SC_METHOD(thread_flashDemux2setPathVa_1_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_grp_nbreadreq_fu_84_p3);
    sensitive << ( flashDemux2setPathVa_1_empty_n );

    SC_METHOD(thread_memWrCmd_V_1_ack_in);
    sensitive << ( memWrCmd_V_1_state );

    SC_METHOD(thread_memWrCmd_V_1_ack_out);
    sensitive << ( memWrCmd_V_TREADY );

    SC_METHOD(thread_memWrCmd_V_1_data_out);
    sensitive << ( memWrCmd_V_1_payload_A );
    sensitive << ( memWrCmd_V_1_payload_B );
    sensitive << ( memWrCmd_V_1_sel );

    SC_METHOD(thread_memWrCmd_V_1_load_A);
    sensitive << ( memWrCmd_V_1_sel_wr );
    sensitive << ( memWrCmd_V_1_state_cmp_full );

    SC_METHOD(thread_memWrCmd_V_1_load_B);
    sensitive << ( memWrCmd_V_1_sel_wr );
    sensitive << ( memWrCmd_V_1_state_cmp_full );

    SC_METHOD(thread_memWrCmd_V_1_sel);
    sensitive << ( memWrCmd_V_1_sel_rd );

    SC_METHOD(thread_memWrCmd_V_1_state_cmp_full);
    sensitive << ( memWrCmd_V_1_state );

    SC_METHOD(thread_memWrCmd_V_1_vld_in);
    sensitive << ( ap_done_reg );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( ap_predicate_op31_write_state2 );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_memWrCmd_V_1_vld_out);
    sensitive << ( memWrCmd_V_1_state );

    SC_METHOD(thread_memWrCmd_V_TDATA);
    sensitive << ( memWrCmd_V_1_data_out );

    SC_METHOD(thread_memWrCmd_V_TDATA_blk_n);
    sensitive << ( ap_predicate_op31_write_state2 );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_predicate_op41_write_state3 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( memWrCmd_V_1_state );

    SC_METHOD(thread_memWrCmd_V_TVALID);
    sensitive << ( memWrCmd_V_1_state );

    SC_METHOD(thread_memWrData_V_V_1_ack_in);
    sensitive << ( memWrData_V_V_1_state );

    SC_METHOD(thread_memWrData_V_V_1_ack_out);
    sensitive << ( memWrData_V_V_TREADY );

    SC_METHOD(thread_memWrData_V_V_1_data_in);
    sensitive << ( ap_predicate_op31_write_state2 );
    sensitive << ( ap_predicate_op34_write_state2 );
    sensitive << ( tmp_V_54_reg_243 );
    sensitive << ( tmp_V_reg_256 );
    sensitive << ( ap_condition_353 );

    SC_METHOD(thread_memWrData_V_V_1_data_out);
    sensitive << ( memWrData_V_V_1_payload_A );
    sensitive << ( memWrData_V_V_1_payload_B );
    sensitive << ( memWrData_V_V_1_sel );

    SC_METHOD(thread_memWrData_V_V_1_load_A);
    sensitive << ( memWrData_V_V_1_sel_wr );
    sensitive << ( memWrData_V_V_1_state_cmp_full );

    SC_METHOD(thread_memWrData_V_V_1_load_B);
    sensitive << ( memWrData_V_V_1_sel_wr );
    sensitive << ( memWrData_V_V_1_state_cmp_full );

    SC_METHOD(thread_memWrData_V_V_1_sel);
    sensitive << ( memWrData_V_V_1_sel_rd );

    SC_METHOD(thread_memWrData_V_V_1_state_cmp_full);
    sensitive << ( memWrData_V_V_1_state );

    SC_METHOD(thread_memWrData_V_V_1_vld_in);
    sensitive << ( ap_done_reg );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( ap_predicate_op31_write_state2 );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_predicate_op34_write_state2 );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_memWrData_V_V_1_vld_out);
    sensitive << ( memWrData_V_V_1_state );

    SC_METHOD(thread_memWrData_V_V_TDATA);
    sensitive << ( memWrData_V_V_1_data_out );

    SC_METHOD(thread_memWrData_V_V_TDATA_blk_n);
    sensitive << ( ap_predicate_op31_write_state2 );
    sensitive << ( ap_predicate_op34_write_state2 );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_predicate_op41_write_state3 );
    sensitive << ( ap_predicate_op46_write_state3 );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( memWrData_V_V_1_state );

    SC_METHOD(thread_memWrData_V_V_TVALID);
    sensitive << ( memWrData_V_V_1_state );

    SC_METHOD(thread_op2_assign_fu_146_p3);
    sensitive << ( tmp_s_fu_136_p4 );

    SC_METHOD(thread_setCtrlWord_address_s_fu_122_p1);
    sensitive << ( flashDemux2setPathMe_1_dout );

    SC_METHOD(thread_setCtrlWord_count_V_fu_166_p3);
    sensitive << ( tmp_s_fu_136_p4 );
    sensitive << ( tmp_197_i_fu_154_p2 );
    sensitive << ( tmp_68_i_fu_160_p2 );

    SC_METHOD(thread_tmp_197_i_fu_154_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );
    sensitive << ( tmp_length_V_load_ne_fu_126_p4 );
    sensitive << ( op2_assign_fu_146_p3 );

    SC_METHOD(thread_tmp_2_cast_fu_216_p1);
    sensitive << ( tmp_2_fu_210_p3 );

    SC_METHOD(thread_tmp_2_fu_210_p3);
    sensitive << ( setCtrlWord_address_s_reg_233 );
    sensitive << ( setCtrlWord_count_V_reg_238 );

    SC_METHOD(thread_tmp_445_nbreadreq_fu_76_p3);
    sensitive << ( flashDemux2setPathMe_1_empty_n );

    SC_METHOD(thread_tmp_447_fu_196_p3);
    sensitive << ( flashDemux2setPathVa_1_dout );

    SC_METHOD(thread_tmp_451_fu_178_p3);
    sensitive << ( flashDemux2setPathVa_1_dout );

    SC_METHOD(thread_tmp_68_i_fu_160_p2);
    sensitive << ( tmp_s_fu_136_p4 );

    SC_METHOD(thread_tmp_V_54_fu_174_p1);
    sensitive << ( flashDemux2setPathVa_1_dout );

    SC_METHOD(thread_tmp_V_fu_192_p1);
    sensitive << ( flashDemux2setPathVa_1_dout );

    SC_METHOD(thread_tmp_length_V_load_ne_fu_126_p4);
    sensitive << ( flashDemux2setPathMe_1_dout );

    SC_METHOD(thread_tmp_s_fu_136_p4);
    sensitive << ( flashDemux2setPathMe_1_dout );

    SC_METHOD(thread_ap_NS_iter0_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_ap_NS_iter1_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter0_fsm_state1 );
    sensitive << ( ap_CS_iter1_fsm );
    sensitive << ( flashDemux2setPathMe_1_empty_n );
    sensitive << ( ap_predicate_op9_read_state1 );
    sensitive << ( flashDemux2setPathVa_1_empty_n );
    sensitive << ( ap_predicate_op23_read_state1 );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    SC_METHOD(thread_ap_NS_iter2_fsm);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_iter2_fsm );
    sensitive << ( memWrCmd_V_1_ack_in );
    sensitive << ( memWrData_V_V_1_ack_in );
    sensitive << ( ap_block_state2_io );
    sensitive << ( ap_CS_iter1_fsm_state2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_CS_iter2_fsm_state3 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_iter0_fsm = "1";
    ap_CS_iter1_fsm = "01";
    ap_CS_iter2_fsm = "01";
    flashSetState_load_reg_221 = "0";
    tmp_445_reg_225 = "0";
    tmp_448_reg_229 = "0";
    tmp_451_reg_248 = "0";
    tmp_reg_252 = "0";
    flashSetState_load_reg_221_pp0_iter1_reg = "0";
    tmp_445_reg_225_pp0_iter1_reg = "0";
    tmp_448_reg_229_pp0_iter1_reg = "0";
    tmp_451_reg_248_pp0_iter1_reg = "0";
    tmp_reg_252_pp0_iter1_reg = "0";
    memWrCmd_V_1_payload_A = "000000000000000000000000000000000000000000000000";
    memWrCmd_V_1_payload_B = "000000000000000000000000000000000000000000000000";
    memWrCmd_V_1_sel_rd = SC_LOGIC_0;
    memWrCmd_V_1_sel_wr = SC_LOGIC_0;
    memWrCmd_V_1_state = "00";
    memWrData_V_V_1_payload_A = "0000000000000000000000000000000000000000000000000000000000000000";
    memWrData_V_V_1_payload_B = "0000000000000000000000000000000000000000000000000000000000000000";
    memWrData_V_V_1_sel_rd = SC_LOGIC_0;
    memWrData_V_V_1_sel_wr = SC_LOGIC_0;
    memWrData_V_V_1_state = "00";
    flashSetState = "0";
    setCtrlWord_address_s_reg_233 = "00000000000000000000000000000000";
    setCtrlWord_count_V_reg_238 = "0000000000000";
    tmp_V_54_reg_243 = "0000000000000000000000000000000000000000000000000000000000000000";
    tmp_V_reg_256 = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "flashSetPathNoFilter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, flashDemux2setPathMe_1_dout, "(port)flashDemux2setPathMe_1_dout");
    sc_trace(mVcdFile, flashDemux2setPathMe_1_empty_n, "(port)flashDemux2setPathMe_1_empty_n");
    sc_trace(mVcdFile, flashDemux2setPathMe_1_read, "(port)flashDemux2setPathMe_1_read");
    sc_trace(mVcdFile, flashDemux2setPathVa_1_dout, "(port)flashDemux2setPathVa_1_dout");
    sc_trace(mVcdFile, flashDemux2setPathVa_1_empty_n, "(port)flashDemux2setPathVa_1_empty_n");
    sc_trace(mVcdFile, flashDemux2setPathVa_1_read, "(port)flashDemux2setPathVa_1_read");
    sc_trace(mVcdFile, memWrCmd_V_TREADY, "(port)memWrCmd_V_TREADY");
    sc_trace(mVcdFile, memWrData_V_V_TREADY, "(port)memWrData_V_V_TREADY");
    sc_trace(mVcdFile, memWrCmd_V_TDATA, "(port)memWrCmd_V_TDATA");
    sc_trace(mVcdFile, memWrCmd_V_TVALID, "(port)memWrCmd_V_TVALID");
    sc_trace(mVcdFile, memWrData_V_V_TDATA, "(port)memWrData_V_V_TDATA");
    sc_trace(mVcdFile, memWrData_V_V_TVALID, "(port)memWrData_V_V_TVALID");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_iter0_fsm, "ap_CS_iter0_fsm");
    sc_trace(mVcdFile, ap_CS_iter0_fsm_state1, "ap_CS_iter0_fsm_state1");
    sc_trace(mVcdFile, ap_CS_iter1_fsm, "ap_CS_iter1_fsm");
    sc_trace(mVcdFile, ap_CS_iter1_fsm_state0, "ap_CS_iter1_fsm_state0");
    sc_trace(mVcdFile, ap_CS_iter2_fsm, "ap_CS_iter2_fsm");
    sc_trace(mVcdFile, ap_CS_iter2_fsm_state0, "ap_CS_iter2_fsm_state0");
    sc_trace(mVcdFile, tmp_445_nbreadreq_fu_76_p3, "tmp_445_nbreadreq_fu_76_p3");
    sc_trace(mVcdFile, grp_nbreadreq_fu_84_p3, "grp_nbreadreq_fu_84_p3");
    sc_trace(mVcdFile, ap_predicate_op9_read_state1, "ap_predicate_op9_read_state1");
    sc_trace(mVcdFile, ap_predicate_op23_read_state1, "ap_predicate_op23_read_state1");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, memWrCmd_V_1_ack_in, "memWrCmd_V_1_ack_in");
    sc_trace(mVcdFile, flashSetState_load_reg_221, "flashSetState_load_reg_221");
    sc_trace(mVcdFile, tmp_445_reg_225, "tmp_445_reg_225");
    sc_trace(mVcdFile, tmp_448_reg_229, "tmp_448_reg_229");
    sc_trace(mVcdFile, tmp_451_reg_248, "tmp_451_reg_248");
    sc_trace(mVcdFile, ap_predicate_op31_write_state2, "ap_predicate_op31_write_state2");
    sc_trace(mVcdFile, memWrData_V_V_1_ack_in, "memWrData_V_V_1_ack_in");
    sc_trace(mVcdFile, tmp_reg_252, "tmp_reg_252");
    sc_trace(mVcdFile, ap_predicate_op34_write_state2, "ap_predicate_op34_write_state2");
    sc_trace(mVcdFile, ap_block_state2_io, "ap_block_state2_io");
    sc_trace(mVcdFile, ap_CS_iter1_fsm_state2, "ap_CS_iter1_fsm_state2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, flashSetState_load_reg_221_pp0_iter1_reg, "flashSetState_load_reg_221_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_445_reg_225_pp0_iter1_reg, "tmp_445_reg_225_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_448_reg_229_pp0_iter1_reg, "tmp_448_reg_229_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_451_reg_248_pp0_iter1_reg, "tmp_451_reg_248_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_predicate_op41_write_state3, "ap_predicate_op41_write_state3");
    sc_trace(mVcdFile, tmp_reg_252_pp0_iter1_reg, "tmp_reg_252_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_predicate_op46_write_state3, "ap_predicate_op46_write_state3");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_CS_iter2_fsm_state3, "ap_CS_iter2_fsm_state3");
    sc_trace(mVcdFile, memWrCmd_V_1_data_out, "memWrCmd_V_1_data_out");
    sc_trace(mVcdFile, memWrCmd_V_1_vld_in, "memWrCmd_V_1_vld_in");
    sc_trace(mVcdFile, memWrCmd_V_1_vld_out, "memWrCmd_V_1_vld_out");
    sc_trace(mVcdFile, memWrCmd_V_1_ack_out, "memWrCmd_V_1_ack_out");
    sc_trace(mVcdFile, memWrCmd_V_1_payload_A, "memWrCmd_V_1_payload_A");
    sc_trace(mVcdFile, memWrCmd_V_1_payload_B, "memWrCmd_V_1_payload_B");
    sc_trace(mVcdFile, memWrCmd_V_1_sel_rd, "memWrCmd_V_1_sel_rd");
    sc_trace(mVcdFile, memWrCmd_V_1_sel_wr, "memWrCmd_V_1_sel_wr");
    sc_trace(mVcdFile, memWrCmd_V_1_sel, "memWrCmd_V_1_sel");
    sc_trace(mVcdFile, memWrCmd_V_1_load_A, "memWrCmd_V_1_load_A");
    sc_trace(mVcdFile, memWrCmd_V_1_load_B, "memWrCmd_V_1_load_B");
    sc_trace(mVcdFile, memWrCmd_V_1_state, "memWrCmd_V_1_state");
    sc_trace(mVcdFile, memWrCmd_V_1_state_cmp_full, "memWrCmd_V_1_state_cmp_full");
    sc_trace(mVcdFile, memWrData_V_V_1_data_in, "memWrData_V_V_1_data_in");
    sc_trace(mVcdFile, memWrData_V_V_1_data_out, "memWrData_V_V_1_data_out");
    sc_trace(mVcdFile, memWrData_V_V_1_vld_in, "memWrData_V_V_1_vld_in");
    sc_trace(mVcdFile, memWrData_V_V_1_vld_out, "memWrData_V_V_1_vld_out");
    sc_trace(mVcdFile, memWrData_V_V_1_ack_out, "memWrData_V_V_1_ack_out");
    sc_trace(mVcdFile, memWrData_V_V_1_payload_A, "memWrData_V_V_1_payload_A");
    sc_trace(mVcdFile, memWrData_V_V_1_payload_B, "memWrData_V_V_1_payload_B");
    sc_trace(mVcdFile, memWrData_V_V_1_sel_rd, "memWrData_V_V_1_sel_rd");
    sc_trace(mVcdFile, memWrData_V_V_1_sel_wr, "memWrData_V_V_1_sel_wr");
    sc_trace(mVcdFile, memWrData_V_V_1_sel, "memWrData_V_V_1_sel");
    sc_trace(mVcdFile, memWrData_V_V_1_load_A, "memWrData_V_V_1_load_A");
    sc_trace(mVcdFile, memWrData_V_V_1_load_B, "memWrData_V_V_1_load_B");
    sc_trace(mVcdFile, memWrData_V_V_1_state, "memWrData_V_V_1_state");
    sc_trace(mVcdFile, memWrData_V_V_1_state_cmp_full, "memWrData_V_V_1_state_cmp_full");
    sc_trace(mVcdFile, flashSetState, "flashSetState");
    sc_trace(mVcdFile, memWrCmd_V_TDATA_blk_n, "memWrCmd_V_TDATA_blk_n");
    sc_trace(mVcdFile, memWrData_V_V_TDATA_blk_n, "memWrData_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, flashDemux2setPathMe_1_blk_n, "flashDemux2setPathMe_1_blk_n");
    sc_trace(mVcdFile, flashDemux2setPathVa_1_blk_n, "flashDemux2setPathVa_1_blk_n");
    sc_trace(mVcdFile, setCtrlWord_address_s_fu_122_p1, "setCtrlWord_address_s_fu_122_p1");
    sc_trace(mVcdFile, setCtrlWord_address_s_reg_233, "setCtrlWord_address_s_reg_233");
    sc_trace(mVcdFile, setCtrlWord_count_V_fu_166_p3, "setCtrlWord_count_V_fu_166_p3");
    sc_trace(mVcdFile, setCtrlWord_count_V_reg_238, "setCtrlWord_count_V_reg_238");
    sc_trace(mVcdFile, tmp_V_54_fu_174_p1, "tmp_V_54_fu_174_p1");
    sc_trace(mVcdFile, tmp_V_54_reg_243, "tmp_V_54_reg_243");
    sc_trace(mVcdFile, tmp_451_fu_178_p3, "tmp_451_fu_178_p3");
    sc_trace(mVcdFile, tmp_V_fu_192_p1, "tmp_V_fu_192_p1");
    sc_trace(mVcdFile, tmp_V_reg_256, "tmp_V_reg_256");
    sc_trace(mVcdFile, tmp_447_fu_196_p3, "tmp_447_fu_196_p3");
    sc_trace(mVcdFile, tmp_2_cast_fu_216_p1, "tmp_2_cast_fu_216_p1");
    sc_trace(mVcdFile, tmp_s_fu_136_p4, "tmp_s_fu_136_p4");
    sc_trace(mVcdFile, tmp_length_V_load_ne_fu_126_p4, "tmp_length_V_load_ne_fu_126_p4");
    sc_trace(mVcdFile, op2_assign_fu_146_p3, "op2_assign_fu_146_p3");
    sc_trace(mVcdFile, tmp_197_i_fu_154_p2, "tmp_197_i_fu_154_p2");
    sc_trace(mVcdFile, tmp_68_i_fu_160_p2, "tmp_68_i_fu_160_p2");
    sc_trace(mVcdFile, tmp_2_fu_210_p3, "tmp_2_fu_210_p3");
    sc_trace(mVcdFile, ap_NS_iter0_fsm, "ap_NS_iter0_fsm");
    sc_trace(mVcdFile, ap_NS_iter1_fsm, "ap_NS_iter1_fsm");
    sc_trace(mVcdFile, ap_NS_iter2_fsm, "ap_NS_iter2_fsm");
    sc_trace(mVcdFile, ap_condition_473, "ap_condition_473");
    sc_trace(mVcdFile, ap_condition_472, "ap_condition_472");
    sc_trace(mVcdFile, ap_condition_353, "ap_condition_353");
#endif

    }
}

flashSetPathNoFilter::~flashSetPathNoFilter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void flashSetPathNoFilter::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_iter0_fsm = ap_ST_iter0_fsm_state1;
    } else {
        ap_CS_iter0_fsm = ap_NS_iter0_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_iter1_fsm = ap_ST_iter1_fsm_state0;
    } else {
        ap_CS_iter1_fsm = ap_NS_iter1_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_iter2_fsm = ap_ST_iter2_fsm_state0;
    } else {
        ap_CS_iter2_fsm = ap_NS_iter2_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
                    !(esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        flashSetState = ap_const_lv1_0;
    } else {
        if (esl_seteq<1,1,1>(ap_condition_472.read(), ap_const_boolean_1)) {
            if ((esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_447_fu_196_p3.read()))) {
                flashSetState = ap_const_lv1_0;
            } else if (esl_seteq<1,1,1>(ap_condition_473.read(), ap_const_boolean_1)) {
                flashSetState = ap_const_lv1_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        flashSetState_load_reg_221 = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()))) {
            flashSetState_load_reg_221 = flashSetState.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        flashSetState_load_reg_221_pp0_iter1_reg = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()))) {
            flashSetState_load_reg_221_pp0_iter1_reg = flashSetState_load_reg_221.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrCmd_V_1_payload_A = ap_const_lv48_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_load_A.read())) {
            memWrCmd_V_1_payload_A = tmp_2_cast_fu_216_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrCmd_V_1_payload_B = ap_const_lv48_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_load_B.read())) {
            memWrCmd_V_1_payload_B = tmp_2_cast_fu_216_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrCmd_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_vld_out.read()))) {
            memWrCmd_V_1_sel_rd =  (sc_logic) (~memWrCmd_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrCmd_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_ack_in.read()))) {
            memWrCmd_V_1_sel_wr =  (sc_logic) (~memWrCmd_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrCmd_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, memWrCmd_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, memWrCmd_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_2)))) {
            memWrCmd_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, memWrCmd_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, memWrCmd_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_1)))) {
            memWrCmd_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(memWrCmd_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, memWrCmd_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, memWrCmd_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_ack_out.read()))))) {
            memWrCmd_V_1_state = ap_const_lv2_3;
        } else {
            memWrCmd_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrData_V_V_1_payload_A = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_load_A.read())) {
            memWrData_V_V_1_payload_A = memWrData_V_V_1_data_in.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrData_V_V_1_payload_B = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_load_B.read())) {
            memWrData_V_V_1_payload_B = memWrData_V_V_1_data_in.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrData_V_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_vld_out.read()))) {
            memWrData_V_V_1_sel_rd =  (sc_logic) (~memWrData_V_V_1_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrData_V_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_ack_in.read()))) {
            memWrData_V_V_1_sel_wr =  (sc_logic) (~memWrData_V_V_1_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        memWrData_V_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, memWrData_V_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, memWrData_V_V_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, memWrData_V_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, memWrData_V_V_1_state.read())))) {
            memWrData_V_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, memWrData_V_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, memWrData_V_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, memWrData_V_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, memWrData_V_V_1_state.read())))) {
            memWrData_V_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, memWrData_V_V_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, memWrData_V_V_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, memWrData_V_V_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, memWrData_V_V_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, memWrData_V_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_ack_out.read()))))) {
            memWrData_V_V_1_state = ap_const_lv2_3;
        } else {
            memWrData_V_V_1_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        setCtrlWord_address_s_reg_233 = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            setCtrlWord_address_s_reg_233 = setCtrlWord_address_s_fu_122_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        setCtrlWord_count_V_reg_238 = ap_const_lv13_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            setCtrlWord_count_V_reg_238 = setCtrlWord_count_V_fu_166_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_445_reg_225 = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_0) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            tmp_445_reg_225 =  (sc_lv<1>) (flashDemux2setPathMe_1_empty_n.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_445_reg_225_pp0_iter1_reg = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()))) {
            tmp_445_reg_225_pp0_iter1_reg = tmp_445_reg_225.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_448_reg_229 = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(tmp_445_nbreadreq_fu_76_p3.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            tmp_448_reg_229 =  (sc_lv<1>) (flashDemux2setPathVa_1_empty_n.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_448_reg_229_pp0_iter1_reg = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()))) {
            tmp_448_reg_229_pp0_iter1_reg = tmp_448_reg_229.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_451_reg_248 = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            tmp_451_reg_248 = flashDemux2setPathVa_1_dout.read().range(64, 64);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_451_reg_248_pp0_iter1_reg = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()))) {
            tmp_451_reg_248_pp0_iter1_reg = tmp_451_reg_248.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_V_54_reg_243 = ap_const_lv64_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            tmp_V_54_reg_243 = tmp_V_54_fu_174_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_V_reg_256 = ap_const_lv64_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            tmp_V_reg_256 = tmp_V_fu_192_p1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_reg_252 = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
             esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
            tmp_reg_252 =  (sc_lv<1>) (flashDemux2setPathVa_1_empty_n.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_reg_252_pp0_iter1_reg = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()))) {
            tmp_reg_252_pp0_iter1_reg = tmp_reg_252.read();
        }
    }
}

void flashSetPathNoFilter::thread_ap_CS_iter0_fsm_state1() {
    ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm.read()[0];
}

void flashSetPathNoFilter::thread_ap_CS_iter1_fsm_state0() {
    ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm.read()[0];
}

void flashSetPathNoFilter::thread_ap_CS_iter1_fsm_state2() {
    ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm.read()[1];
}

void flashSetPathNoFilter::thread_ap_CS_iter2_fsm_state0() {
    ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm.read()[0];
}

void flashSetPathNoFilter::thread_ap_CS_iter2_fsm_state3() {
    ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm.read()[1];
}

void flashSetPathNoFilter::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)));
}

void flashSetPathNoFilter::thread_ap_block_state2_io() {
    ap_block_state2_io = ((esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read())) || (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read()) && 
  esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_write_state2.read())));
}

void flashSetPathNoFilter::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void flashSetPathNoFilter::thread_ap_block_state3_io() {
    ap_block_state3_io = ((esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op41_write_state3.read())) || (esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op41_write_state3.read())) || (esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op46_write_state3.read())));
}

void flashSetPathNoFilter::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0));
}

void flashSetPathNoFilter::thread_ap_condition_353() {
    ap_condition_353 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || ((esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0)) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()))));
}

void flashSetPathNoFilter::thread_ap_condition_472() {
    ap_condition_472 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, grp_nbreadreq_fu_84_p3.read()) && !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))));
}

void flashSetPathNoFilter::thread_ap_condition_473() {
    ap_condition_473 = (esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_445_nbreadreq_fu_76_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_451_fu_178_p3.read()));
}

void flashSetPathNoFilter::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void flashSetPathNoFilter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void flashSetPathNoFilter::thread_ap_predicate_op23_read_state1() {
    ap_predicate_op23_read_state1 = (esl_seteq<1,1,1>(ap_const_lv1_1, grp_nbreadreq_fu_84_p3.read()) && esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_1));
}

void flashSetPathNoFilter::thread_ap_predicate_op31_write_state2() {
    ap_predicate_op31_write_state2 = (esl_seteq<1,1,1>(ap_const_lv1_0, flashSetState_load_reg_221.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_445_reg_225.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_448_reg_229.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_451_reg_248.read()));
}

void flashSetPathNoFilter::thread_ap_predicate_op34_write_state2() {
    ap_predicate_op34_write_state2 = (esl_seteq<1,1,1>(ap_const_lv1_1, flashSetState_load_reg_221.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_252.read()));
}

void flashSetPathNoFilter::thread_ap_predicate_op41_write_state3() {
    ap_predicate_op41_write_state3 = (esl_seteq<1,1,1>(ap_const_lv1_0, flashSetState_load_reg_221_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_445_reg_225_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_448_reg_229_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_451_reg_248_pp0_iter1_reg.read()));
}

void flashSetPathNoFilter::thread_ap_predicate_op46_write_state3() {
    ap_predicate_op46_write_state3 = (esl_seteq<1,1,1>(ap_const_lv1_1, flashSetState_load_reg_221_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_252_pp0_iter1_reg.read()));
}

void flashSetPathNoFilter::thread_ap_predicate_op9_read_state1() {
    ap_predicate_op9_read_state1 = (esl_seteq<1,1,1>(flashSetState.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_445_nbreadreq_fu_76_p3.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, grp_nbreadreq_fu_84_p3.read()));
}

void flashSetPathNoFilter::thread_ap_ready() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void flashSetPathNoFilter::thread_flashDemux2setPathMe_1_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()))) {
        flashDemux2setPathMe_1_blk_n = flashDemux2setPathMe_1_empty_n.read();
    } else {
        flashDemux2setPathMe_1_blk_n = ap_const_logic_1;
    }
}

void flashSetPathNoFilter::thread_flashDemux2setPathMe_1_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
        flashDemux2setPathMe_1_read = ap_const_logic_1;
    } else {
        flashDemux2setPathMe_1_read = ap_const_logic_0;
    }
}

void flashSetPathNoFilter::thread_flashDemux2setPathVa_1_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
          !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1) && 
          !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read())))) {
        flashDemux2setPathVa_1_blk_n = flashDemux2setPathVa_1_empty_n.read();
    } else {
        flashDemux2setPathVa_1_blk_n = ap_const_logic_1;
    }
}

void flashSetPathNoFilter::thread_flashDemux2setPathVa_1_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1) && 
          !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1) && 
          !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))))) {
        flashDemux2setPathVa_1_read = ap_const_logic_1;
    } else {
        flashDemux2setPathVa_1_read = ap_const_logic_0;
    }
}

void flashSetPathNoFilter::thread_grp_nbreadreq_fu_84_p3() {
    grp_nbreadreq_fu_84_p3 =  (sc_lv<1>) (flashDemux2setPathVa_1_empty_n.read());
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_ack_in() {
    memWrCmd_V_1_ack_in = memWrCmd_V_1_state.read()[1];
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_ack_out() {
    memWrCmd_V_1_ack_out = memWrCmd_V_TREADY.read();
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, memWrCmd_V_1_sel.read())) {
        memWrCmd_V_1_data_out = memWrCmd_V_1_payload_B.read();
    } else {
        memWrCmd_V_1_data_out = memWrCmd_V_1_payload_A.read();
    }
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_load_A() {
    memWrCmd_V_1_load_A = (memWrCmd_V_1_state_cmp_full.read() & ~memWrCmd_V_1_sel_wr.read());
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_load_B() {
    memWrCmd_V_1_load_B = (memWrCmd_V_1_sel_wr.read() & memWrCmd_V_1_state_cmp_full.read());
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_sel() {
    memWrCmd_V_1_sel = memWrCmd_V_1_sel_rd.read();
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_state_cmp_full() {
    memWrCmd_V_1_state_cmp_full =  (sc_logic) ((!memWrCmd_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(memWrCmd_V_1_state.read() != ap_const_lv2_1))[0];
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))))) {
        memWrCmd_V_1_vld_in = ap_const_logic_1;
    } else {
        memWrCmd_V_1_vld_in = ap_const_logic_0;
    }
}

void flashSetPathNoFilter::thread_memWrCmd_V_1_vld_out() {
    memWrCmd_V_1_vld_out = memWrCmd_V_1_state.read()[0];
}

void flashSetPathNoFilter::thread_memWrCmd_V_TDATA() {
    memWrCmd_V_TDATA = memWrCmd_V_1_data_out.read();
}

void flashSetPathNoFilter::thread_memWrCmd_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op41_write_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read())))) {
        memWrCmd_V_TDATA_blk_n = memWrCmd_V_1_state.read()[1];
    } else {
        memWrCmd_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void flashSetPathNoFilter::thread_memWrCmd_V_TVALID() {
    memWrCmd_V_TVALID = memWrCmd_V_1_state.read()[0];
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_ack_in() {
    memWrData_V_V_1_ack_in = memWrData_V_V_1_state.read()[1];
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_ack_out() {
    memWrData_V_V_1_ack_out = memWrData_V_V_TREADY.read();
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_data_in() {
    if (esl_seteq<1,1,1>(ap_condition_353.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_write_state2.read())) {
            memWrData_V_V_1_data_in = tmp_V_reg_256.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read())) {
            memWrData_V_V_1_data_in = tmp_V_54_reg_243.read();
        } else {
            memWrData_V_V_1_data_in = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        memWrData_V_V_1_data_in = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, memWrData_V_V_1_sel.read())) {
        memWrData_V_V_1_data_out = memWrData_V_V_1_payload_B.read();
    } else {
        memWrData_V_V_1_data_out = memWrData_V_V_1_payload_A.read();
    }
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_load_A() {
    memWrData_V_V_1_load_A = (memWrData_V_V_1_state_cmp_full.read() & ~memWrData_V_V_1_sel_wr.read());
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_load_B() {
    memWrData_V_V_1_load_B = (memWrData_V_V_1_sel_wr.read() & memWrData_V_V_1_state_cmp_full.read());
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_sel() {
    memWrData_V_V_1_sel = memWrData_V_V_1_sel_rd.read();
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_state_cmp_full() {
    memWrData_V_V_1_state_cmp_full =  (sc_logic) ((!memWrData_V_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(memWrData_V_V_1_state.read() != ap_const_lv2_1))[0];
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_vld_in() {
    if (((esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))))) || 
         (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_write_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))))))) {
        memWrData_V_V_1_vld_in = ap_const_logic_1;
    } else {
        memWrData_V_V_1_vld_in = ap_const_logic_0;
    }
}

void flashSetPathNoFilter::thread_memWrData_V_V_1_vld_out() {
    memWrData_V_V_1_vld_out = memWrData_V_V_1_state.read()[0];
}

void flashSetPathNoFilter::thread_memWrData_V_V_TDATA() {
    memWrData_V_V_TDATA = memWrData_V_V_1_data_out.read();
}

void flashSetPathNoFilter::thread_memWrData_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op31_write_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op41_write_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_write_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op46_write_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read())))) {
        memWrData_V_V_TDATA_blk_n = memWrData_V_V_1_state.read()[1];
    } else {
        memWrData_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void flashSetPathNoFilter::thread_memWrData_V_V_TVALID() {
    memWrData_V_V_TVALID = memWrData_V_V_1_state.read()[0];
}

void flashSetPathNoFilter::thread_op2_assign_fu_146_p3() {
    op2_assign_fu_146_p3 = esl_concat<13,3>(tmp_s_fu_136_p4.read(), ap_const_lv3_0);
}

void flashSetPathNoFilter::thread_setCtrlWord_address_s_fu_122_p1() {
    setCtrlWord_address_s_fu_122_p1 = flashDemux2setPathMe_1_dout.read().range(32-1, 0);
}

void flashSetPathNoFilter::thread_setCtrlWord_count_V_fu_166_p3() {
    setCtrlWord_count_V_fu_166_p3 = (!tmp_197_i_fu_154_p2.read()[0].is_01())? sc_lv<13>(): ((tmp_197_i_fu_154_p2.read()[0].to_bool())? tmp_68_i_fu_160_p2.read(): tmp_s_fu_136_p4.read());
}

void flashSetPathNoFilter::thread_tmp_197_i_fu_154_p2() {
    tmp_197_i_fu_154_p2 = (!tmp_length_V_load_ne_fu_126_p4.read().is_01() || !op2_assign_fu_146_p3.read().is_01())? sc_lv<1>(): (sc_biguint<16>(tmp_length_V_load_ne_fu_126_p4.read()) > sc_biguint<16>(op2_assign_fu_146_p3.read()));
}

void flashSetPathNoFilter::thread_tmp_2_cast_fu_216_p1() {
    tmp_2_cast_fu_216_p1 = esl_sext<48,45>(tmp_2_fu_210_p3.read());
}

void flashSetPathNoFilter::thread_tmp_2_fu_210_p3() {
    tmp_2_fu_210_p3 = esl_concat<13,32>(setCtrlWord_count_V_reg_238.read(), setCtrlWord_address_s_reg_233.read());
}

void flashSetPathNoFilter::thread_tmp_445_nbreadreq_fu_76_p3() {
    tmp_445_nbreadreq_fu_76_p3 =  (sc_lv<1>) (flashDemux2setPathMe_1_empty_n.read());
}

void flashSetPathNoFilter::thread_tmp_447_fu_196_p3() {
    tmp_447_fu_196_p3 = flashDemux2setPathVa_1_dout.read().range(65, 65);
}

void flashSetPathNoFilter::thread_tmp_451_fu_178_p3() {
    tmp_451_fu_178_p3 = flashDemux2setPathVa_1_dout.read().range(64, 64);
}

void flashSetPathNoFilter::thread_tmp_68_i_fu_160_p2() {
    tmp_68_i_fu_160_p2 = (!ap_const_lv13_1.is_01() || !tmp_s_fu_136_p4.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_1) + sc_biguint<13>(tmp_s_fu_136_p4.read()));
}

void flashSetPathNoFilter::thread_tmp_V_54_fu_174_p1() {
    tmp_V_54_fu_174_p1 = flashDemux2setPathVa_1_dout.read().range(64-1, 0);
}

void flashSetPathNoFilter::thread_tmp_V_fu_192_p1() {
    tmp_V_fu_192_p1 = flashDemux2setPathVa_1_dout.read().range(64-1, 0);
}

void flashSetPathNoFilter::thread_tmp_length_V_load_ne_fu_126_p4() {
    tmp_length_V_load_ne_fu_126_p4 = flashDemux2setPathMe_1_dout.read().range(47, 32);
}

void flashSetPathNoFilter::thread_tmp_s_fu_136_p4() {
    tmp_s_fu_136_p4 = flashDemux2setPathMe_1_dout.read().range(47, 35);
}

void flashSetPathNoFilter::thread_ap_NS_iter0_fsm() {
    switch (ap_CS_iter0_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
break;
        default : 
            ap_NS_iter0_fsm =  (sc_lv<1>) ("X");
            break;
    }
}

void flashSetPathNoFilter::thread_ap_NS_iter1_fsm() {
    switch (ap_CS_iter1_fsm.read().to_uint64()) {
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1))) && !(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()))) {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            } else if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && (esl_seteq<1,1,1>(ap_const_logic_0, ap_CS_iter0_fsm_state1.read()) || 
  (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()) && 
   (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || 
    esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || 
    (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
     esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || 
    (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
     esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || 
    (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
     esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1))))))) {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            } else {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            }
            break;
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op23_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathVa_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(flashDemux2setPathMe_1_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_predicate_op9_read_state1.read(), ap_const_boolean_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter0_fsm_state1.read()))) {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            } else {
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            }
            break;
        default : 
            ap_NS_iter1_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void flashSetPathNoFilter::thread_ap_NS_iter2_fsm() {
    switch (ap_CS_iter2_fsm.read().to_uint64()) {
        case 2 : 
            if ((!(esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state2_io.read()))) {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            } else if ((!(esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && (esl_seteq<1,1,1>(ap_const_logic_0, ap_CS_iter1_fsm_state2.read()) || 
  (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()) && 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()))))) {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            } else {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            }
            break;
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter2_fsm_state3.read()) && 
  (esl_seteq<1,1,1>(memWrCmd_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(memWrData_V_V_1_ack_in.read(), ap_const_logic_0) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_iter1_fsm_state2.read()))) {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            } else {
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            }
            break;
        default : 
            ap_NS_iter2_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

