-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flashSetPathNoFilter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    flashDemux2setPathMe_1_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    flashDemux2setPathMe_1_empty_n : IN STD_LOGIC;
    flashDemux2setPathMe_1_read : OUT STD_LOGIC;
    flashDemux2setPathVa_1_dout : IN STD_LOGIC_VECTOR (65 downto 0);
    flashDemux2setPathVa_1_empty_n : IN STD_LOGIC;
    flashDemux2setPathVa_1_read : OUT STD_LOGIC;
    memWrCmd_V_TREADY : IN STD_LOGIC;
    memWrData_V_V_TREADY : IN STD_LOGIC;
    memWrCmd_V_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    memWrCmd_V_TVALID : OUT STD_LOGIC;
    memWrData_V_V_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    memWrData_V_V_TVALID : OUT STD_LOGIC );
end;


architecture behav of flashSetPathNoFilter is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal tmp_445_nbreadreq_fu_76_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_nbreadreq_fu_84_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op9_read_state1 : BOOLEAN;
    signal ap_predicate_op23_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal memWrCmd_V_1_ack_in : STD_LOGIC;
    signal flashSetState_load_reg_221 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_445_reg_225 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_448_reg_229 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_451_reg_248 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_predicate_op31_write_state2 : BOOLEAN;
    signal memWrData_V_V_1_ack_in : STD_LOGIC;
    signal tmp_reg_252 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_predicate_op34_write_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal flashSetState_load_reg_221_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_445_reg_225_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_448_reg_229_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_451_reg_248_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_predicate_op41_write_state3 : BOOLEAN;
    signal tmp_reg_252_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_predicate_op46_write_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal memWrCmd_V_1_data_out : STD_LOGIC_VECTOR (47 downto 0);
    signal memWrCmd_V_1_vld_in : STD_LOGIC;
    signal memWrCmd_V_1_vld_out : STD_LOGIC;
    signal memWrCmd_V_1_ack_out : STD_LOGIC;
    signal memWrCmd_V_1_payload_A : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal memWrCmd_V_1_payload_B : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal memWrCmd_V_1_sel_rd : STD_LOGIC := '0';
    signal memWrCmd_V_1_sel_wr : STD_LOGIC := '0';
    signal memWrCmd_V_1_sel : STD_LOGIC;
    signal memWrCmd_V_1_load_A : STD_LOGIC;
    signal memWrCmd_V_1_load_B : STD_LOGIC;
    signal memWrCmd_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal memWrCmd_V_1_state_cmp_full : STD_LOGIC;
    signal memWrData_V_V_1_data_in : STD_LOGIC_VECTOR (63 downto 0);
    signal memWrData_V_V_1_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal memWrData_V_V_1_vld_in : STD_LOGIC;
    signal memWrData_V_V_1_vld_out : STD_LOGIC;
    signal memWrData_V_V_1_ack_out : STD_LOGIC;
    signal memWrData_V_V_1_payload_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal memWrData_V_V_1_payload_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal memWrData_V_V_1_sel_rd : STD_LOGIC := '0';
    signal memWrData_V_V_1_sel_wr : STD_LOGIC := '0';
    signal memWrData_V_V_1_sel : STD_LOGIC;
    signal memWrData_V_V_1_load_A : STD_LOGIC;
    signal memWrData_V_V_1_load_B : STD_LOGIC;
    signal memWrData_V_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal memWrData_V_V_1_state_cmp_full : STD_LOGIC;
    signal flashSetState : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal memWrCmd_V_TDATA_blk_n : STD_LOGIC;
    signal memWrData_V_V_TDATA_blk_n : STD_LOGIC;
    signal flashDemux2setPathMe_1_blk_n : STD_LOGIC;
    signal flashDemux2setPathVa_1_blk_n : STD_LOGIC;
    signal setCtrlWord_address_s_fu_122_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal setCtrlWord_address_s_reg_233 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal setCtrlWord_count_V_fu_166_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal setCtrlWord_count_V_reg_238 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal tmp_V_54_fu_174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_V_54_reg_243 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal tmp_451_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_fu_192_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_V_reg_256 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal tmp_447_fu_196_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_cast_fu_216_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_s_fu_136_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_length_V_load_ne_fu_126_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal op2_assign_fu_146_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_197_i_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_68_i_fu_160_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_2_fu_210_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_condition_473 : BOOLEAN;
    signal ap_condition_472 : BOOLEAN;
    signal ap_condition_353 : BOOLEAN;


begin




    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    flashSetState_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                flashSetState <= ap_const_lv1_0;
            else
                if ((ap_const_boolean_1 = ap_condition_472)) then
                    if (((tmp_447_fu_196_p3 = ap_const_lv1_1) and (flashSetState = ap_const_lv1_1))) then 
                        flashSetState <= ap_const_lv1_0;
                    elsif ((ap_const_boolean_1 = ap_condition_473)) then 
                        flashSetState <= ap_const_lv1_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    flashSetState_load_reg_221_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                flashSetState_load_reg_221 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    flashSetState_load_reg_221 <= flashSetState;
                end if; 
            end if;
        end if;
    end process;


    flashSetState_load_reg_221_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                flashSetState_load_reg_221_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    flashSetState_load_reg_221_pp0_iter1_reg <= flashSetState_load_reg_221;
                end if; 
            end if;
        end if;
    end process;


    memWrCmd_V_1_payload_A_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrCmd_V_1_payload_A <= ap_const_lv48_0;
            else
                if ((memWrCmd_V_1_load_A = ap_const_logic_1)) then 
                    memWrCmd_V_1_payload_A <= tmp_2_cast_fu_216_p1;
                end if; 
            end if;
        end if;
    end process;


    memWrCmd_V_1_payload_B_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrCmd_V_1_payload_B <= ap_const_lv48_0;
            else
                if ((memWrCmd_V_1_load_B = ap_const_logic_1)) then 
                    memWrCmd_V_1_payload_B <= tmp_2_cast_fu_216_p1;
                end if; 
            end if;
        end if;
    end process;


    memWrCmd_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrCmd_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((memWrCmd_V_1_ack_out = ap_const_logic_1) and (memWrCmd_V_1_vld_out = ap_const_logic_1))) then 
                                        memWrCmd_V_1_sel_rd <= not(memWrCmd_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    memWrCmd_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrCmd_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((memWrCmd_V_1_ack_in = ap_const_logic_1) and (memWrCmd_V_1_vld_in = ap_const_logic_1))) then 
                                        memWrCmd_V_1_sel_wr <= not(memWrCmd_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    memWrCmd_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrCmd_V_1_state <= ap_const_lv2_0;
            else
                if ((((memWrCmd_V_1_vld_in = ap_const_logic_0) and (memWrCmd_V_1_state = ap_const_lv2_2)) or ((memWrCmd_V_1_vld_in = ap_const_logic_0) and (memWrCmd_V_1_ack_out = ap_const_logic_1) and (memWrCmd_V_1_state = ap_const_lv2_3)))) then 
                    memWrCmd_V_1_state <= ap_const_lv2_2;
                elsif ((((memWrCmd_V_1_ack_out = ap_const_logic_0) and (memWrCmd_V_1_state = ap_const_lv2_1)) or ((memWrCmd_V_1_ack_out = ap_const_logic_0) and (memWrCmd_V_1_vld_in = ap_const_logic_1) and (memWrCmd_V_1_state = ap_const_lv2_3)))) then 
                    memWrCmd_V_1_state <= ap_const_lv2_1;
                elsif (((not(((memWrCmd_V_1_vld_in = ap_const_logic_0) and (memWrCmd_V_1_ack_out = ap_const_logic_1))) and not(((memWrCmd_V_1_ack_out = ap_const_logic_0) and (memWrCmd_V_1_vld_in = ap_const_logic_1))) and (memWrCmd_V_1_state = ap_const_lv2_3)) or ((memWrCmd_V_1_ack_out = ap_const_logic_1) and (memWrCmd_V_1_state = ap_const_lv2_1)) or ((memWrCmd_V_1_vld_in = ap_const_logic_1) and (memWrCmd_V_1_state = ap_const_lv2_2)))) then 
                    memWrCmd_V_1_state <= ap_const_lv2_3;
                else 
                    memWrCmd_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    memWrData_V_V_1_payload_A_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrData_V_V_1_payload_A <= ap_const_lv64_0;
            else
                if ((memWrData_V_V_1_load_A = ap_const_logic_1)) then 
                    memWrData_V_V_1_payload_A <= memWrData_V_V_1_data_in;
                end if; 
            end if;
        end if;
    end process;


    memWrData_V_V_1_payload_B_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrData_V_V_1_payload_B <= ap_const_lv64_0;
            else
                if ((memWrData_V_V_1_load_B = ap_const_logic_1)) then 
                    memWrData_V_V_1_payload_B <= memWrData_V_V_1_data_in;
                end if; 
            end if;
        end if;
    end process;


    memWrData_V_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrData_V_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((memWrData_V_V_1_ack_out = ap_const_logic_1) and (memWrData_V_V_1_vld_out = ap_const_logic_1))) then 
                                        memWrData_V_V_1_sel_rd <= not(memWrData_V_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    memWrData_V_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrData_V_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((memWrData_V_V_1_vld_in = ap_const_logic_1) and (memWrData_V_V_1_ack_in = ap_const_logic_1))) then 
                                        memWrData_V_V_1_sel_wr <= not(memWrData_V_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    memWrData_V_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                memWrData_V_V_1_state <= ap_const_lv2_0;
            else
                if ((((memWrData_V_V_1_vld_in = ap_const_logic_0) and (memWrData_V_V_1_state = ap_const_lv2_2)) or ((memWrData_V_V_1_vld_in = ap_const_logic_0) and (memWrData_V_V_1_ack_out = ap_const_logic_1) and (memWrData_V_V_1_state = ap_const_lv2_3)))) then 
                    memWrData_V_V_1_state <= ap_const_lv2_2;
                elsif ((((memWrData_V_V_1_ack_out = ap_const_logic_0) and (memWrData_V_V_1_state = ap_const_lv2_1)) or ((memWrData_V_V_1_ack_out = ap_const_logic_0) and (memWrData_V_V_1_vld_in = ap_const_logic_1) and (memWrData_V_V_1_state = ap_const_lv2_3)))) then 
                    memWrData_V_V_1_state <= ap_const_lv2_1;
                elsif (((not(((memWrData_V_V_1_vld_in = ap_const_logic_0) and (memWrData_V_V_1_ack_out = ap_const_logic_1))) and not(((memWrData_V_V_1_ack_out = ap_const_logic_0) and (memWrData_V_V_1_vld_in = ap_const_logic_1))) and (memWrData_V_V_1_state = ap_const_lv2_3)) or ((memWrData_V_V_1_ack_out = ap_const_logic_1) and (memWrData_V_V_1_state = ap_const_lv2_1)) or ((memWrData_V_V_1_vld_in = ap_const_logic_1) and (memWrData_V_V_1_state = ap_const_lv2_2)))) then 
                    memWrData_V_V_1_state <= ap_const_lv2_3;
                else 
                    memWrData_V_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    setCtrlWord_address_s_reg_233_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                setCtrlWord_address_s_reg_233 <= ap_const_lv32_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
                    setCtrlWord_address_s_reg_233 <= setCtrlWord_address_s_fu_122_p1;
                end if; 
            end if;
        end if;
    end process;


    setCtrlWord_count_V_reg_238_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                setCtrlWord_count_V_reg_238 <= ap_const_lv13_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
                    setCtrlWord_count_V_reg_238 <= setCtrlWord_count_V_fu_166_p3;
                end if; 
            end if;
        end if;
    end process;


    tmp_445_reg_225_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_445_reg_225 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (flashSetState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    tmp_445_reg_225 <= (0=>flashDemux2setPathMe_1_empty_n, others=>'-');
                end if; 
            end if;
        end if;
    end process;


    tmp_445_reg_225_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_445_reg_225_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    tmp_445_reg_225_pp0_iter1_reg <= tmp_445_reg_225;
                end if; 
            end if;
        end if;
    end process;


    tmp_448_reg_229_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_448_reg_229 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (tmp_445_nbreadreq_fu_76_p3 = ap_const_lv1_1) and (flashSetState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    tmp_448_reg_229 <= (0=>flashDemux2setPathVa_1_empty_n, others=>'-');
                end if; 
            end if;
        end if;
    end process;


    tmp_448_reg_229_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_448_reg_229_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    tmp_448_reg_229_pp0_iter1_reg <= tmp_448_reg_229;
                end if; 
            end if;
        end if;
    end process;


    tmp_451_reg_248_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_451_reg_248 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
                    tmp_451_reg_248 <= flashDemux2setPathVa_1_dout(64 downto 64);
                end if; 
            end if;
        end if;
    end process;


    tmp_451_reg_248_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_451_reg_248_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    tmp_451_reg_248_pp0_iter1_reg <= tmp_451_reg_248;
                end if; 
            end if;
        end if;
    end process;


    tmp_V_54_reg_243_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_V_54_reg_243 <= ap_const_lv64_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
                    tmp_V_54_reg_243 <= tmp_V_54_fu_174_p1;
                end if; 
            end if;
        end if;
    end process;


    tmp_V_reg_256_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_V_reg_256 <= ap_const_lv64_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op23_read_state1 = ap_const_boolean_1))) then 
                    tmp_V_reg_256 <= tmp_V_fu_192_p1;
                end if; 
            end if;
        end if;
    end process;


    tmp_reg_252_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_reg_252 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (flashSetState = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                    tmp_reg_252 <= (0=>flashDemux2setPathVa_1_empty_n, others=>'-');
                end if; 
            end if;
        end if;
    end process;


    tmp_reg_252_pp0_iter1_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_reg_252_pp0_iter1_reg <= ap_const_lv1_0;
            else
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    tmp_reg_252_pp0_iter1_reg <= tmp_reg_252;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_iter0_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_iter0_fsm, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) and not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_done_reg, ap_CS_iter2_fsm, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_io))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and ((ap_const_logic_0 = ap_CS_iter1_fsm_state2) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io))))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_io_assign_proc : process(memWrCmd_V_1_ack_in, ap_predicate_op31_write_state2, memWrData_V_V_1_ack_in, ap_predicate_op34_write_state2)
    begin
                ap_block_state2_io <= (((memWrData_V_V_1_ack_in = ap_const_logic_0) and (ap_predicate_op31_write_state2 = ap_const_boolean_1)) or ((memWrCmd_V_1_ack_in = ap_const_logic_0) and (ap_predicate_op31_write_state2 = ap_const_boolean_1)) or ((memWrData_V_V_1_ack_in = ap_const_logic_0) and (ap_predicate_op34_write_state2 = ap_const_boolean_1)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_predicate_op41_write_state3, ap_predicate_op46_write_state3)
    begin
                ap_block_state3_io <= (((memWrCmd_V_1_ack_in = ap_const_logic_0) and (ap_predicate_op41_write_state3 = ap_const_boolean_1)) or ((memWrData_V_V_1_ack_in = ap_const_logic_0) and (ap_predicate_op46_write_state3 = ap_const_boolean_1)) or ((memWrData_V_V_1_ack_in = ap_const_logic_0) and (ap_predicate_op41_write_state3 = ap_const_boolean_1)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_condition_353_assign_proc : process(ap_done_reg, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_CS_iter1_fsm_state2, ap_CS_iter2_fsm_state3)
    begin
                ap_condition_353 <= (not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2));
    end process;


    ap_condition_472_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2setPathMe_1_empty_n, grp_nbreadreq_fu_84_p3, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
                ap_condition_472 <= (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (grp_nbreadreq_fu_84_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_473_assign_proc : process(tmp_445_nbreadreq_fu_76_p3, flashSetState, tmp_451_fu_178_p3)
    begin
                ap_condition_473 <= ((tmp_451_fu_178_p3 = ap_const_lv1_1) and (tmp_445_nbreadreq_fu_76_p3 = ap_const_lv1_1) and (flashSetState = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op23_read_state1_assign_proc : process(grp_nbreadreq_fu_84_p3, flashSetState)
    begin
                ap_predicate_op23_read_state1 <= ((grp_nbreadreq_fu_84_p3 = ap_const_lv1_1) and (flashSetState = ap_const_lv1_1));
    end process;


    ap_predicate_op31_write_state2_assign_proc : process(flashSetState_load_reg_221, tmp_445_reg_225, tmp_448_reg_229, tmp_451_reg_248)
    begin
                ap_predicate_op31_write_state2 <= ((tmp_451_reg_248 = ap_const_lv1_1) and (tmp_448_reg_229 = ap_const_lv1_1) and (tmp_445_reg_225 = ap_const_lv1_1) and (flashSetState_load_reg_221 = ap_const_lv1_0));
    end process;


    ap_predicate_op34_write_state2_assign_proc : process(flashSetState_load_reg_221, tmp_reg_252)
    begin
                ap_predicate_op34_write_state2 <= ((flashSetState_load_reg_221 = ap_const_lv1_1) and (tmp_reg_252 = ap_const_lv1_1));
    end process;


    ap_predicate_op41_write_state3_assign_proc : process(flashSetState_load_reg_221_pp0_iter1_reg, tmp_445_reg_225_pp0_iter1_reg, tmp_448_reg_229_pp0_iter1_reg, tmp_451_reg_248_pp0_iter1_reg)
    begin
                ap_predicate_op41_write_state3 <= ((tmp_451_reg_248_pp0_iter1_reg = ap_const_lv1_1) and (tmp_448_reg_229_pp0_iter1_reg = ap_const_lv1_1) and (tmp_445_reg_225_pp0_iter1_reg = ap_const_lv1_1) and (flashSetState_load_reg_221_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op46_write_state3_assign_proc : process(flashSetState_load_reg_221_pp0_iter1_reg, tmp_reg_252_pp0_iter1_reg)
    begin
                ap_predicate_op46_write_state3 <= ((tmp_reg_252_pp0_iter1_reg = ap_const_lv1_1) and (flashSetState_load_reg_221_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op9_read_state1_assign_proc : process(tmp_445_nbreadreq_fu_76_p3, grp_nbreadreq_fu_84_p3, flashSetState)
    begin
                ap_predicate_op9_read_state1 <= ((grp_nbreadreq_fu_84_p3 = ap_const_lv1_1) and (tmp_445_nbreadreq_fu_76_p3 = ap_const_lv1_1) and (flashSetState = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    flashDemux2setPathMe_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
            flashDemux2setPathMe_1_blk_n <= flashDemux2setPathMe_1_empty_n;
        else 
            flashDemux2setPathMe_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    flashDemux2setPathMe_1_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
            flashDemux2setPathMe_1_read <= ap_const_logic_1;
        else 
            flashDemux2setPathMe_1_read <= ap_const_logic_0;
        end if; 
    end process;


    flashDemux2setPathVa_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) then 
            flashDemux2setPathVa_1_blk_n <= flashDemux2setPathVa_1_empty_n;
        else 
            flashDemux2setPathVa_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    flashDemux2setPathVa_1_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_iter0_fsm_state1, flashDemux2setPathMe_1_empty_n, ap_predicate_op9_read_state1, flashDemux2setPathVa_1_empty_n, ap_predicate_op23_read_state1, memWrCmd_V_1_ack_in, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathVa_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((flashDemux2setPathMe_1_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_io)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))) then 
            flashDemux2setPathVa_1_read <= ap_const_logic_1;
        else 
            flashDemux2setPathVa_1_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_nbreadreq_fu_84_p3 <= (0=>flashDemux2setPathVa_1_empty_n, others=>'-');
    memWrCmd_V_1_ack_in <= memWrCmd_V_1_state(1);
    memWrCmd_V_1_ack_out <= memWrCmd_V_TREADY;

    memWrCmd_V_1_data_out_assign_proc : process(memWrCmd_V_1_payload_A, memWrCmd_V_1_payload_B, memWrCmd_V_1_sel)
    begin
        if ((memWrCmd_V_1_sel = ap_const_logic_1)) then 
            memWrCmd_V_1_data_out <= memWrCmd_V_1_payload_B;
        else 
            memWrCmd_V_1_data_out <= memWrCmd_V_1_payload_A;
        end if; 
    end process;

    memWrCmd_V_1_load_A <= (memWrCmd_V_1_state_cmp_full and not(memWrCmd_V_1_sel_wr));
    memWrCmd_V_1_load_B <= (memWrCmd_V_1_state_cmp_full and memWrCmd_V_1_sel_wr);
    memWrCmd_V_1_sel <= memWrCmd_V_1_sel_rd;
    memWrCmd_V_1_state_cmp_full <= '0' when (memWrCmd_V_1_state = ap_const_lv2_1) else '1';

    memWrCmd_V_1_vld_in_assign_proc : process(ap_done_reg, memWrCmd_V_1_ack_in, ap_predicate_op31_write_state2, memWrData_V_V_1_ack_in, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op31_write_state2 = ap_const_boolean_1))) then 
            memWrCmd_V_1_vld_in <= ap_const_logic_1;
        else 
            memWrCmd_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    memWrCmd_V_1_vld_out <= memWrCmd_V_1_state(0);
    memWrCmd_V_TDATA <= memWrCmd_V_1_data_out;

    memWrCmd_V_TDATA_blk_n_assign_proc : process(ap_predicate_op31_write_state2, ap_CS_iter1_fsm_state2, ap_predicate_op41_write_state3, ap_CS_iter2_fsm_state3, memWrCmd_V_1_state)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op31_write_state2 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op41_write_state3 = ap_const_boolean_1)))) then 
            memWrCmd_V_TDATA_blk_n <= memWrCmd_V_1_state(1);
        else 
            memWrCmd_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    memWrCmd_V_TVALID <= memWrCmd_V_1_state(0);
    memWrData_V_V_1_ack_in <= memWrData_V_V_1_state(1);
    memWrData_V_V_1_ack_out <= memWrData_V_V_TREADY;

    memWrData_V_V_1_data_in_assign_proc : process(ap_predicate_op31_write_state2, ap_predicate_op34_write_state2, tmp_V_54_reg_243, tmp_V_reg_256, ap_condition_353)
    begin
        if ((ap_const_boolean_1 = ap_condition_353)) then
            if ((ap_predicate_op34_write_state2 = ap_const_boolean_1)) then 
                memWrData_V_V_1_data_in <= tmp_V_reg_256;
            elsif ((ap_predicate_op31_write_state2 = ap_const_boolean_1)) then 
                memWrData_V_V_1_data_in <= tmp_V_54_reg_243;
            else 
                memWrData_V_V_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            memWrData_V_V_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    memWrData_V_V_1_data_out_assign_proc : process(memWrData_V_V_1_payload_A, memWrData_V_V_1_payload_B, memWrData_V_V_1_sel)
    begin
        if ((memWrData_V_V_1_sel = ap_const_logic_1)) then 
            memWrData_V_V_1_data_out <= memWrData_V_V_1_payload_B;
        else 
            memWrData_V_V_1_data_out <= memWrData_V_V_1_payload_A;
        end if; 
    end process;

    memWrData_V_V_1_load_A <= (memWrData_V_V_1_state_cmp_full and not(memWrData_V_V_1_sel_wr));
    memWrData_V_V_1_load_B <= (memWrData_V_V_1_state_cmp_full and memWrData_V_V_1_sel_wr);
    memWrData_V_V_1_sel <= memWrData_V_V_1_sel_rd;
    memWrData_V_V_1_state_cmp_full <= '0' when (memWrData_V_V_1_state = ap_const_lv2_1) else '1';

    memWrData_V_V_1_vld_in_assign_proc : process(ap_done_reg, memWrCmd_V_1_ack_in, ap_predicate_op31_write_state2, memWrData_V_V_1_ack_in, ap_predicate_op34_write_state2, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op31_write_state2 = ap_const_boolean_1)) or (not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((memWrCmd_V_1_ack_in = ap_const_logic_0) or (memWrData_V_V_1_ack_in = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_io))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op34_write_state2 = ap_const_boolean_1)))) then 
            memWrData_V_V_1_vld_in <= ap_const_logic_1;
        else 
            memWrData_V_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    memWrData_V_V_1_vld_out <= memWrData_V_V_1_state(0);
    memWrData_V_V_TDATA <= memWrData_V_V_1_data_out;

    memWrData_V_V_TDATA_blk_n_assign_proc : process(ap_predicate_op31_write_state2, ap_predicate_op34_write_state2, ap_CS_iter1_fsm_state2, ap_predicate_op41_write_state3, ap_predicate_op46_write_state3, ap_CS_iter2_fsm_state3, memWrData_V_V_1_state)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op31_write_state2 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op46_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op41_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op34_write_state2 = ap_const_boolean_1)))) then 
            memWrData_V_V_TDATA_blk_n <= memWrData_V_V_1_state(1);
        else 
            memWrData_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    memWrData_V_V_TVALID <= memWrData_V_V_1_state(0);
    op2_assign_fu_146_p3 <= (tmp_s_fu_136_p4 & ap_const_lv3_0);
    setCtrlWord_address_s_fu_122_p1 <= flashDemux2setPathMe_1_dout(32 - 1 downto 0);
    setCtrlWord_count_V_fu_166_p3 <= 
        tmp_68_i_fu_160_p2 when (tmp_197_i_fu_154_p2(0) = '1') else 
        tmp_s_fu_136_p4;
    tmp_197_i_fu_154_p2 <= "1" when (unsigned(tmp_length_V_load_ne_fu_126_p4) > unsigned(op2_assign_fu_146_p3)) else "0";
        tmp_2_cast_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_210_p3),48));

    tmp_2_fu_210_p3 <= (setCtrlWord_count_V_reg_238 & setCtrlWord_address_s_reg_233);
    tmp_445_nbreadreq_fu_76_p3 <= (0=>flashDemux2setPathMe_1_empty_n, others=>'-');
    tmp_447_fu_196_p3 <= flashDemux2setPathVa_1_dout(65 downto 65);
    tmp_451_fu_178_p3 <= flashDemux2setPathVa_1_dout(64 downto 64);
    tmp_68_i_fu_160_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(tmp_s_fu_136_p4));
    tmp_V_54_fu_174_p1 <= flashDemux2setPathVa_1_dout(64 - 1 downto 0);
    tmp_V_fu_192_p1 <= flashDemux2setPathVa_1_dout(64 - 1 downto 0);
    tmp_length_V_load_ne_fu_126_p4 <= flashDemux2setPathMe_1_dout(47 downto 32);
    tmp_s_fu_136_p4 <= flashDemux2setPathMe_1_dout(47 downto 35);
end behav;
